---
name: Build & Release RPM

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [ "br1" ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    container: "rockylinux:8"
    env:
      SERVICE_NAME: example-package
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get the clone and working directory name
        run: |
          echo "CLONE_DIR=/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "WORKING_DIR=/__w/${{ env.SERVICE_NAME }}-${{ env.TAG }}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v3

      - name: move files
        run: cp -a ${{ env.CLONE_DIR }} ${{ env.WORKING_DIR }}


      - name: Tar up source
        working-directory: /__w/
        run: >
          tar -zcf
          ${{ env.WORKING_DIR }}_111.tar.gz
          ${{ env.SERVICE_NAME }}-${{ env.TAG }}


      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.WORKING_DIR }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
