
---
name: Build & Release RPM

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [ "br1" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: "rockylinux:8"
    env:
      SERVICE_NAME: example-package
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
