---
name: Build & Release UI

on:
  push:
    branches:
      - 'preprod'
  pull_request:
    branches: [ "preprod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: "rockylinux:8"
    
    env:
      SERVICE_NAME: ada-ui
      
    steps:

        - name: Get the clone and working directory name
          run: |
            echo "CLONE_DIR=/__w/${{ github.event.repository.name }}" >> $GITHUB_ENV
            echo "WORKING_DIR=/__w/${{ env.SERVICE_NAME }}-${{github.event.number  }}" >> $GITHUB_ENV


        - name: checkout
          uses: actions/checkout@v3
          

        - name: move files
          run: cp -a ${{ env.CLONE_DIR }} ${{ env.WORKING_DIR }}
          
        - name: install dependencies
          run: dnf module install -y nodejs:18 


        # - name: Use Node.js
          # uses: actions/setup-node@v3
           # with:
            # node-version: 18.x

        - name: Tar up source
          working-directory: /__w/
          run: >
           tar -zcf
           ${{ env.SERVICE_NAME }}-${{github.event.number}}.tar.gz 
           ${{ env.WORKING_DIR }}


        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ${{ env.SERVICE_NAME }}-${{github.event.number}}.tar.gz
            tag: ${{ github.ref }}
            overwrite: true
